/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoApp;

import java.util.List;
import model.Project;
import model.Task;
import controller.ProjectController;
import controller.TaskController;

public class App {
    public static void main(String[] args) {
        
        //ProjectController projectController = new ProjectController();
        //Project project = new Project();

        //project.setName("Projeto teste Apache NetBeans");
        //project.setDescription("Descrição do projeto teste Apache NetBeans");
        //projectController.save(project);

        //project.setId(4);
        //project.setName("Novo nome do projeto NetBeans");
        //project.setDescription("Nova descrição Apache");
        //projectController.update(project);

        //List<Project> projects = projectController.getAll();
        //System.out.println(("Total de projetos = " + projects.size()));

        //projectController.removeById(6);

        //TaskController taskController = new TaskController();
        //Task task = new Task();

        //task.setName("Tarefa 5 NetBeans");
        //task.setIdProject(5);
        //task.setDescription("Descrição da tarefa 1 NetBeans");
        //task.setNotes("Sem notas");
        //taskController.save(task);

        //task.setIdProject(5);
        //task.setId(4);
        //task.setName("Tarefa da IDE velha virou da IDE nova");
        //task.setDescription("Nova descrição NetBeans");

        //taskController.update(task);

        //taskController.removeById(3);


        //List<Task> tasks = taskController.getAll(5);
        //System.out.println("Total de tarefas = " + tasks.size());
    }

    Object getGreeting() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}